package com.model;

public class Exam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.id
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.questionid
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    private Integer questionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.question
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.choiceA
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    private String choicea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.choiceB
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    private String choiceb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.choiceC
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    private String choicec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.choiceD
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    private String choiced;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.fs
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    private Integer fs;
    private String anwser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.id
     *
     * @return the value of exam.id
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.id
     *
     * @param id the value for exam.id
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.questionid
     *
     * @return the value of exam.questionid
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.questionid
     *
     * @param questionid the value for exam.questionid
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.question
     *
     * @return the value of exam.question
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.question
     *
     * @param question the value for exam.question
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.choiceA
     *
     * @return the value of exam.choiceA
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public String getChoicea() {
        return choicea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.choiceA
     *
     * @param choicea the value for exam.choiceA
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public void setChoicea(String choicea) {
        this.choicea = choicea == null ? null : choicea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.choiceB
     *
     * @return the value of exam.choiceB
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public String getChoiceb() {
        return choiceb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.choiceB
     *
     * @param choiceb the value for exam.choiceB
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public void setChoiceb(String choiceb) {
        this.choiceb = choiceb == null ? null : choiceb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.choiceC
     *
     * @return the value of exam.choiceC
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public String getChoicec() {
        return choicec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.choiceC
     *
     * @param choicec the value for exam.choiceC
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public void setChoicec(String choicec) {
        this.choicec = choicec == null ? null : choicec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.choiceD
     *
     * @return the value of exam.choiceD
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public String getChoiced() {
        return choiced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.choiceD
     *
     * @param choiced the value for exam.choiceD
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public void setChoiced(String choiced) {
        this.choiced = choiced == null ? null : choiced.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.fs
     *
     * @return the value of exam.fs
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public Integer getFs() {
        return fs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.fs
     *
     * @param fs the value for exam.fs
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public void setFs(Integer fs) {
        this.fs = fs;
    }

	public String getAnwser() {
		return anwser;
	}

	public void setAnwser(String anwser) {
		this.anwser = anwser;
	}
    
}