package com.model;

import java.util.ArrayList;
import java.util.List;

public class ExamExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public ExamExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andQuestionidIsNull() {
            addCriterion("questionid is null");
            return (Criteria) this;
        }

        public Criteria andQuestionidIsNotNull() {
            addCriterion("questionid is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionidEqualTo(Integer value) {
            addCriterion("questionid =", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidNotEqualTo(Integer value) {
            addCriterion("questionid <>", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidGreaterThan(Integer value) {
            addCriterion("questionid >", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidGreaterThanOrEqualTo(Integer value) {
            addCriterion("questionid >=", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidLessThan(Integer value) {
            addCriterion("questionid <", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidLessThanOrEqualTo(Integer value) {
            addCriterion("questionid <=", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidIn(List<Integer> values) {
            addCriterion("questionid in", values, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidNotIn(List<Integer> values) {
            addCriterion("questionid not in", values, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidBetween(Integer value1, Integer value2) {
            addCriterion("questionid between", value1, value2, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidNotBetween(Integer value1, Integer value2) {
            addCriterion("questionid not between", value1, value2, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionIsNull() {
            addCriterion("question is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIsNotNull() {
            addCriterion("question is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionEqualTo(String value) {
            addCriterion("question =", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotEqualTo(String value) {
            addCriterion("question <>", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionGreaterThan(String value) {
            addCriterion("question >", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionGreaterThanOrEqualTo(String value) {
            addCriterion("question >=", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionLessThan(String value) {
            addCriterion("question <", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionLessThanOrEqualTo(String value) {
            addCriterion("question <=", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionLike(String value) {
            addCriterion("question like", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotLike(String value) {
            addCriterion("question not like", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionIn(List<String> values) {
            addCriterion("question in", values, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotIn(List<String> values) {
            addCriterion("question not in", values, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionBetween(String value1, String value2) {
            addCriterion("question between", value1, value2, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotBetween(String value1, String value2) {
            addCriterion("question not between", value1, value2, "question");
            return (Criteria) this;
        }

        public Criteria andChoiceaIsNull() {
            addCriterion("choiceA is null");
            return (Criteria) this;
        }

        public Criteria andChoiceaIsNotNull() {
            addCriterion("choiceA is not null");
            return (Criteria) this;
        }

        public Criteria andChoiceaEqualTo(String value) {
            addCriterion("choiceA =", value, "choicea");
            return (Criteria) this;
        }

        public Criteria andChoiceaNotEqualTo(String value) {
            addCriterion("choiceA <>", value, "choicea");
            return (Criteria) this;
        }

        public Criteria andChoiceaGreaterThan(String value) {
            addCriterion("choiceA >", value, "choicea");
            return (Criteria) this;
        }

        public Criteria andChoiceaGreaterThanOrEqualTo(String value) {
            addCriterion("choiceA >=", value, "choicea");
            return (Criteria) this;
        }

        public Criteria andChoiceaLessThan(String value) {
            addCriterion("choiceA <", value, "choicea");
            return (Criteria) this;
        }

        public Criteria andChoiceaLessThanOrEqualTo(String value) {
            addCriterion("choiceA <=", value, "choicea");
            return (Criteria) this;
        }

        public Criteria andChoiceaLike(String value) {
            addCriterion("choiceA like", value, "choicea");
            return (Criteria) this;
        }

        public Criteria andChoiceaNotLike(String value) {
            addCriterion("choiceA not like", value, "choicea");
            return (Criteria) this;
        }

        public Criteria andChoiceaIn(List<String> values) {
            addCriterion("choiceA in", values, "choicea");
            return (Criteria) this;
        }

        public Criteria andChoiceaNotIn(List<String> values) {
            addCriterion("choiceA not in", values, "choicea");
            return (Criteria) this;
        }

        public Criteria andChoiceaBetween(String value1, String value2) {
            addCriterion("choiceA between", value1, value2, "choicea");
            return (Criteria) this;
        }

        public Criteria andChoiceaNotBetween(String value1, String value2) {
            addCriterion("choiceA not between", value1, value2, "choicea");
            return (Criteria) this;
        }

        public Criteria andChoicebIsNull() {
            addCriterion("choiceB is null");
            return (Criteria) this;
        }

        public Criteria andChoicebIsNotNull() {
            addCriterion("choiceB is not null");
            return (Criteria) this;
        }

        public Criteria andChoicebEqualTo(String value) {
            addCriterion("choiceB =", value, "choiceb");
            return (Criteria) this;
        }

        public Criteria andChoicebNotEqualTo(String value) {
            addCriterion("choiceB <>", value, "choiceb");
            return (Criteria) this;
        }

        public Criteria andChoicebGreaterThan(String value) {
            addCriterion("choiceB >", value, "choiceb");
            return (Criteria) this;
        }

        public Criteria andChoicebGreaterThanOrEqualTo(String value) {
            addCriterion("choiceB >=", value, "choiceb");
            return (Criteria) this;
        }

        public Criteria andChoicebLessThan(String value) {
            addCriterion("choiceB <", value, "choiceb");
            return (Criteria) this;
        }

        public Criteria andChoicebLessThanOrEqualTo(String value) {
            addCriterion("choiceB <=", value, "choiceb");
            return (Criteria) this;
        }

        public Criteria andChoicebLike(String value) {
            addCriterion("choiceB like", value, "choiceb");
            return (Criteria) this;
        }

        public Criteria andChoicebNotLike(String value) {
            addCriterion("choiceB not like", value, "choiceb");
            return (Criteria) this;
        }

        public Criteria andChoicebIn(List<String> values) {
            addCriterion("choiceB in", values, "choiceb");
            return (Criteria) this;
        }

        public Criteria andChoicebNotIn(List<String> values) {
            addCriterion("choiceB not in", values, "choiceb");
            return (Criteria) this;
        }

        public Criteria andChoicebBetween(String value1, String value2) {
            addCriterion("choiceB between", value1, value2, "choiceb");
            return (Criteria) this;
        }

        public Criteria andChoicebNotBetween(String value1, String value2) {
            addCriterion("choiceB not between", value1, value2, "choiceb");
            return (Criteria) this;
        }

        public Criteria andChoicecIsNull() {
            addCriterion("choiceC is null");
            return (Criteria) this;
        }

        public Criteria andChoicecIsNotNull() {
            addCriterion("choiceC is not null");
            return (Criteria) this;
        }

        public Criteria andChoicecEqualTo(String value) {
            addCriterion("choiceC =", value, "choicec");
            return (Criteria) this;
        }

        public Criteria andChoicecNotEqualTo(String value) {
            addCriterion("choiceC <>", value, "choicec");
            return (Criteria) this;
        }

        public Criteria andChoicecGreaterThan(String value) {
            addCriterion("choiceC >", value, "choicec");
            return (Criteria) this;
        }

        public Criteria andChoicecGreaterThanOrEqualTo(String value) {
            addCriterion("choiceC >=", value, "choicec");
            return (Criteria) this;
        }

        public Criteria andChoicecLessThan(String value) {
            addCriterion("choiceC <", value, "choicec");
            return (Criteria) this;
        }

        public Criteria andChoicecLessThanOrEqualTo(String value) {
            addCriterion("choiceC <=", value, "choicec");
            return (Criteria) this;
        }

        public Criteria andChoicecLike(String value) {
            addCriterion("choiceC like", value, "choicec");
            return (Criteria) this;
        }

        public Criteria andChoicecNotLike(String value) {
            addCriterion("choiceC not like", value, "choicec");
            return (Criteria) this;
        }

        public Criteria andChoicecIn(List<String> values) {
            addCriterion("choiceC in", values, "choicec");
            return (Criteria) this;
        }

        public Criteria andChoicecNotIn(List<String> values) {
            addCriterion("choiceC not in", values, "choicec");
            return (Criteria) this;
        }

        public Criteria andChoicecBetween(String value1, String value2) {
            addCriterion("choiceC between", value1, value2, "choicec");
            return (Criteria) this;
        }

        public Criteria andChoicecNotBetween(String value1, String value2) {
            addCriterion("choiceC not between", value1, value2, "choicec");
            return (Criteria) this;
        }

        public Criteria andChoicedIsNull() {
            addCriterion("choiceD is null");
            return (Criteria) this;
        }

        public Criteria andChoicedIsNotNull() {
            addCriterion("choiceD is not null");
            return (Criteria) this;
        }

        public Criteria andChoicedEqualTo(String value) {
            addCriterion("choiceD =", value, "choiced");
            return (Criteria) this;
        }

        public Criteria andChoicedNotEqualTo(String value) {
            addCriterion("choiceD <>", value, "choiced");
            return (Criteria) this;
        }

        public Criteria andChoicedGreaterThan(String value) {
            addCriterion("choiceD >", value, "choiced");
            return (Criteria) this;
        }

        public Criteria andChoicedGreaterThanOrEqualTo(String value) {
            addCriterion("choiceD >=", value, "choiced");
            return (Criteria) this;
        }

        public Criteria andChoicedLessThan(String value) {
            addCriterion("choiceD <", value, "choiced");
            return (Criteria) this;
        }

        public Criteria andChoicedLessThanOrEqualTo(String value) {
            addCriterion("choiceD <=", value, "choiced");
            return (Criteria) this;
        }

        public Criteria andChoicedLike(String value) {
            addCriterion("choiceD like", value, "choiced");
            return (Criteria) this;
        }

        public Criteria andChoicedNotLike(String value) {
            addCriterion("choiceD not like", value, "choiced");
            return (Criteria) this;
        }

        public Criteria andChoicedIn(List<String> values) {
            addCriterion("choiceD in", values, "choiced");
            return (Criteria) this;
        }

        public Criteria andChoicedNotIn(List<String> values) {
            addCriterion("choiceD not in", values, "choiced");
            return (Criteria) this;
        }

        public Criteria andChoicedBetween(String value1, String value2) {
            addCriterion("choiceD between", value1, value2, "choiced");
            return (Criteria) this;
        }

        public Criteria andChoicedNotBetween(String value1, String value2) {
            addCriterion("choiceD not between", value1, value2, "choiced");
            return (Criteria) this;
        }

        public Criteria andFsIsNull() {
            addCriterion("fs is null");
            return (Criteria) this;
        }

        public Criteria andFsIsNotNull() {
            addCriterion("fs is not null");
            return (Criteria) this;
        }

        public Criteria andFsEqualTo(Integer value) {
            addCriterion("fs =", value, "fs");
            return (Criteria) this;
        }

        public Criteria andFsNotEqualTo(Integer value) {
            addCriterion("fs <>", value, "fs");
            return (Criteria) this;
        }

        public Criteria andFsGreaterThan(Integer value) {
            addCriterion("fs >", value, "fs");
            return (Criteria) this;
        }

        public Criteria andFsGreaterThanOrEqualTo(Integer value) {
            addCriterion("fs >=", value, "fs");
            return (Criteria) this;
        }

        public Criteria andFsLessThan(Integer value) {
            addCriterion("fs <", value, "fs");
            return (Criteria) this;
        }

        public Criteria andFsLessThanOrEqualTo(Integer value) {
            addCriterion("fs <=", value, "fs");
            return (Criteria) this;
        }

        public Criteria andFsIn(List<Integer> values) {
            addCriterion("fs in", values, "fs");
            return (Criteria) this;
        }

        public Criteria andFsNotIn(List<Integer> values) {
            addCriterion("fs not in", values, "fs");
            return (Criteria) this;
        }

        public Criteria andFsBetween(Integer value1, Integer value2) {
            addCriterion("fs between", value1, value2, "fs");
            return (Criteria) this;
        }

        public Criteria andFsNotBetween(Integer value1, Integer value2) {
            addCriterion("fs not between", value1, value2, "fs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 06 18:24:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam
     *
     * @mbggenerated Mon Nov 06 18:24:21 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}