package com.mapper;

import com.model.Clas;
import com.model.ClasExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clas
     *
     * @mbggenerated Sat Oct 28 14:26:24 CST 2017
     */
    int countByExample(ClasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clas
     *
     * @mbggenerated Sat Oct 28 14:26:24 CST 2017
     */
    int deleteByExample(ClasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clas
     *
     * @mbggenerated Sat Oct 28 14:26:24 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clas
     *
     * @mbggenerated Sat Oct 28 14:26:24 CST 2017
     */
    int insert(Clas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clas
     *
     * @mbggenerated Sat Oct 28 14:26:24 CST 2017
     */
    int insertSelective(Clas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clas
     *
     * @mbggenerated Sat Oct 28 14:26:24 CST 2017
     */
    List<Clas> selectByExample(ClasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clas
     *
     * @mbggenerated Sat Oct 28 14:26:24 CST 2017
     */
    Clas selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clas
     *
     * @mbggenerated Sat Oct 28 14:26:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") Clas record, @Param("example") ClasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clas
     *
     * @mbggenerated Sat Oct 28 14:26:24 CST 2017
     */
    int updateByExample(@Param("record") Clas record, @Param("example") ClasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clas
     *
     * @mbggenerated Sat Oct 28 14:26:24 CST 2017
     */
    int updateByPrimaryKeySelective(Clas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clas
     *
     * @mbggenerated Sat Oct 28 14:26:24 CST 2017
     */
    int updateByPrimaryKey(Clas record);
}